[FREELOADER]
DefaultOS=LiveImg_Debug
TimeOut=10

[Display]
TitleText=ClawOS Boot Media
MinimalUI=Yes

[Operating Systems]
Setup="ClawOS Setup (Text Mode)"
LiveImg="ClawOS Live Environment (Graphics Mode)"
LiveImg_RamDisk="ClawOS Live Environment - RamDisk"
==
;; The entries below are for testing and development:
Setup_Debug="Setup (Debug)"
Setup_Screen="Setup (Screen Debug)"
LiveImg_Debug="Live (Debug)"
LiveImg_VBoxDebug="Live (VBox Debug)"
LiveImg_Screen="Live (Screen Debug)"
;; The following entry is an example template:
;LiveImg_LogFile="Live (Log file)"

[Setup]
BootType=ClawOSSetup

[Setup_Debug]
BootType=ClawOSSetup
Options=/DEBUG /DEBUGPORT=COM1 /BAUDRATE=115200 /NOGUIBOOT /SIFOPTIONSOVERRIDE

[Setup_Screen]
BootType=ClawOSSetup
Options=/DEBUG /DEBUGPORT=SCREEN /SIFOPTIONSOVERRIDE

[LiveImg]
BootType=Windows2003
SystemPath=\reactos
Options=/FASTDETECT /MININT

[LiveImg_RamDisk]
BootType=Windows2003
SystemPath=ramdisk(0)\reactos
Options=/FASTDETECT /MININT /RDPATH= /RDEXPORTASCD
;Options=/FASTDETECT /MININT /RDPATH=liveimg.iso /RDEXPORTASCD

[LiveImg_Debug]
BootType=Windows2003
SystemPath=\reactos
Options=/DEBUG /DEBUGPORT=COM1 /BAUDRATE=115200 /SOS /FASTDETECT /MININT

[LiveImg_VBoxDebug]
BootType=Windows2003
SystemPath=\reactos
Options=/DEBUG /DEBUGPORT=VBOX /SOS /FASTDETECT /MININT

[LiveImg_Screen]
BootType=Windows2003
SystemPath=\reactos
Options=/DEBUG /DEBUGPORT=SCREEN /SOS /FASTDETECT /MININT

;[LiveImg_LogFile]
;BootType=Windows2003
;SystemPath=\reactos
;Options=/DEBUG /DEBUGPORT=FILE:\Device\HarddiskX\PartitionY\debug.log /SOS /FASTDETECT /MININT
